version: "3.8"

services:
  db:
    image: postgres
    container_name: ryan-gosling-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ryan-gosling-database:/var/lib/postgresql/data
    networks:
      - ryan-gosling-networks

  ryan-gosling-backend:
    image: ryan-gosling-backend
    build: ./app
    container_name: ryan-gosling-backend
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

      - SECRET_KEY=empty
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

      - SENTRY_DSN=empty
      - TELEGRAM_TOKEN=empty
      - CHAD_GPT_TOKEN=empty
    command:
      - /bin/bash
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py migrate
        python manage.py createsuperuser --noinput
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ryan-gosling-networks

  ryan-gosling-bot:
    image: ryan-gosling-backend
    container_name: ryan-gosling-bot
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

      - SECRET_KEY=empty
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

      - SENTRY_DSN=empty
      - TELEGRAM_TOKEN=empty
      - CHAD_GPT_TOKEN=empty
    volumes:
      - ./app:/code
    command:
      - /bin/bash
      - -c
      - |
        python manage.py execute_tlg_bot
    depends_on:
      - ryan-gosling-backend
    networks:
      - ryan-gosling-networks

networks:
  ryan-gosling-networks:

volumes:
  ryan-gosling-database:
