version: "3.8"

services:
  db:
    image: postgres
    container_name: ryan-gosling-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ryan-gosling-database:/var/lib/postgresql/data
    networks:
      - ryan-gosling-networks

  ryan-gosling-backend:
    image: ryan-gosling-backend
    build: ./app
    container_name: ryan-gosling-backend
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

      - SECRET_KEY="m#t7gx#ho3#ccj7(oo^09u5q(%r&nlcn^0e66ar_iisgn_%o*0"
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

      - SENTRY_DSN=empty
      - TELEGRAM_TOKEN=6978931415:AAEqJH7tInmV8cUjjpZ3blGKv2G3hLa8I84
      - CHAD_GPT_TOKEN=chad-c43846755a0b4043806e15fb28a32f9cud52gu50
    command:
      - /bin/bash
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py migrate
        python manage.py createsuperuser --noinput
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ryan-gosling-networks

  ryan-gosling-bot:
    image: ryan-gosling-backend
    container_name: ryan-gosling-bot
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

      - SECRET_KEY="m#t7gx#ho3#ccj7(oo^09u5q(%r&nlcn^0e66ar_iisgn_%o*0"
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

      - SENTRY_DSN=empty
      - TELEGRAM_TOKEN=6978931415:AAFbxPDrS96VSzNfiTt2xa4Kh21rUwLilq8
      - CHAD_GPT_TOKEN=chad-cf641f157dcc4c40a431d7e40194d3f3744ht3ud
    volumes:
      - ./app:/code
    command:
      - /bin/bash
      - -c
      - |
        python manage.py execute_tlg_bot
    depends_on:
      - ryan-gosling-backend
    networks:
      - ryan-gosling-networks

networks:
  ryan-gosling-networks:

volumes:
  ryan-gosling-database:
