name: Tests

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the image
        uses: docker/bake-action@v3
        with:
          files: docker-compose.yml
          targets: web
          load: true
          set: |
            *.cache-from=type=gha,scope=cached-stage
            *.cache-to=type=gha,scope=cached-stage,mode=max

      - name: Test
        run: |
          docker compose run web pytest 
        run: |
          docker compose run web flake8 .
